# Generated by Django 5.2 on 2026-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='postgres_service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
