# Generated by Django 5.2 on 2026-02-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_project_postgres_service_id_project_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.project'),
        ),
    ]
