# Generated by Django 5.2 on 2026-02-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_project_organization_organization_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='project_id',
        ),
        migrations.AddField(
            model_name='env',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
