# Generated by Django 5.2 on 2026-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_env_project_id_env_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
