# Generated by Django 5.2 on 2026-02-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_default_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='postgres_service_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_id',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, max_length=100, null=True)),
                ('postgres_service_id', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
