# Generated by Django 5.2 on 2026-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_project_postgres_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='volume_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
