# Generated by Django 5.2 on 2026-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_service_volume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='workflow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
