# Generated by Django 5.2 on 2026-02-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_workflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='service',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('database', 'Database')], max_length=100, null=True),
        ),
    ]
