# Generated by Django 5.2 on 2026-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creadentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_auth_token', models.CharField(max_length=255)),
                ('railway_workspace_id', models.CharField(max_length=255)),
                ('raiway_template_id', models.CharField(max_length=255)),
            ],
        ),
    ]
